version: '2'
services:
    storetqvone-app:
        image: storetqvone
        external_links:
            - storetqvone-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/storetqvone?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - :
    storetqvone-mysql:
        extends:
            file: mysql.yml
            service: storetqvone-mysql
